# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fire Fist Media
email: contact@firefistmedia.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to firefistmedia blogging on jekyll with github pages.
  Fire Fist Media is a digital agency specialising in search engine optimisation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://firefistmedia.github.io/" # the base hostname & protocol for your site
twitter_username: firefistmedia
github_username:  firefistmedia

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day
